# Generated by Django 4.2.4 on 2023-12-13 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_tax"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tax",
            options={"verbose_name_plural": "tax"},
        ),
    ]
