# Generated by Django 4.2.4 on 2023-10-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
