# Generated by Django 4.2.4 on 2023-12-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendor", "0003_alter_openinghour_options_and_more"),
        ("orders", "0002_rename_payment_id_order_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="vendors",
            field=models.ManyToManyField(blank=True, to="vendor.vendor"),
        ),
    ]
