# Generated by Django 4.2.4 on 2023-12-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_tax_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
